/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Idempotent sample event batch push */
        post: operations["sync_push_v1_sync_push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Role-checked, idempotent case command */
        post: operations["case_command_v1_cases__case_id__commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptActionCommand */
        AcceptActionCommand: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Expected Version */
            expected_version: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "accept_action";
            payload: components["schemas"]["AcceptActionPayload"];
        };
        /** AcceptActionPayload */
        AcceptActionPayload: {
            /**
             * Action Id
             * Format: uuid
             */
            action_id: string;
            /** Completed At */
            completed_at?: string | null;
            /** Evidence Note */
            evidence_note?: string | null;
        };
        /** AssignCommand */
        AssignCommand: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Expected Version */
            expected_version: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "assign";
            payload: components["schemas"]["AssignPayload"];
        };
        /** AssignPayload */
        AssignPayload: {
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Due At */
            due_at?: string | null;
        };
        /** CanonicalSampleV1 */
        CanonicalSampleV1: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Sample Id
             * Format: uuid
             */
            sample_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            protocol: components["schemas"]["ProtocolRef"];
            /**
             * Kit Lot Id
             * Format: uuid
             */
            kit_lot_id: string;
            /**
             * Captured At Device
             * Format: date-time
             */
            captured_at_device: string;
            /** Timing */
            timing: components["schemas"]["TimingMeasured"] | components["schemas"]["TimingIndeterminate"];
            method: components["schemas"]["Method"];
            observation: components["schemas"]["Observation"];
            /** Evidence Ids */
            evidence_ids?: string[];
            /** Client Build */
            client_build: string;
            data_mode: components["schemas"]["DataMode"];
        };
        /** CloseCommand */
        CloseCommand: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Expected Version */
            expected_version: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "close";
            payload: components["schemas"]["ClosePayload"];
        };
        /**
         * ClosePayload
         * @description api-contracts.md: 'close includes verified_report_id,
         *     retest_sample_id or authorized exemption, action IDs or exemption,
         *     communication_id, disposition and policy_version.' The or-exemption
         *     pattern is enforced below, not just documented - this is what makes
         *     acceptance criterion 1 ('command discriminators reject invalid data')
         *     real rather than type-checking alone.
         */
        ClosePayload: {
            /** Verified Report Id */
            verified_report_id?: string | null;
            /** Verified Report Exemption Reason */
            verified_report_exemption_reason?: string | null;
            /** Retest Sample Id */
            retest_sample_id?: string | null;
            /** Retest Exemption Reason */
            retest_exemption_reason?: string | null;
            /** Action Ids */
            action_ids?: string[];
            /** Action Exemption Reason */
            action_exemption_reason?: string | null;
            /**
             * Communication Id
             * Format: uuid
             */
            communication_id: string;
            /** Disposition */
            disposition: string;
            /** Policy Version */
            policy_version: number;
        };
        /**
         * DataMode
         * @enum {string}
         */
        DataMode: "synthetic" | "research" | "operational";
        /** DismissCommand */
        DismissCommand: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Expected Version */
            expected_version: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "dismiss";
            payload: components["schemas"]["DismissPayload"];
        };
        /** DismissPayload */
        DismissPayload: {
            /** Reason */
            reason: string;
            /** Dismiss Reason */
            dismiss_reason?: ("invalid_capture" | "duplicate" | "not_a_water_source" | "resolved_before_referral") | null;
            /** Disposition */
            disposition?: string | null;
        };
        /**
         * IndicativeFlag
         * @description 'no_flag' means the tested parameter did not trigger that protocol's
         *     review rule - it is never a potability/safety claim (AGENTS.md).
         * @enum {string}
         */
        IndicativeFlag: "no_flag" | "review" | "uncertain" | "invalid";
        /** LinkRetestCommand */
        LinkRetestCommand: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Expected Version */
            expected_version: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "link_retest";
            payload: components["schemas"]["LinkRetestPayload"];
        };
        /** LinkRetestPayload */
        LinkRetestPayload: {
            /** Retest Sample Id */
            retest_sample_id?: string | null;
        };
        /**
         * Method
         * @enum {string}
         */
        Method: "assisted" | "manual";
        /**
         * Observation
         * @description Machine suggestion and human observation are kept as distinct
         *     optional fields (machine_bin / manual_bin / selected_bin) rather than
         *     ever collapsed into one 'result' field - this is the AGENTS.md
         *     provenance-separation rule expressed as a schema shape, not a comment.
         */
        Observation: {
            /** Machine Bin */
            machine_bin?: string | null;
            /** Manual Bin */
            manual_bin?: string | null;
            /** Selected Bin */
            selected_bin?: string | null;
            indicative_flag: components["schemas"]["IndicativeFlag"];
            /** Quality Reasons */
            quality_reasons?: string[];
            /** Model Version */
            model_version?: string | null;
            /** Calibration Version */
            calibration_version?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Override Reason */
            override_reason?: string | null;
        };
        /** ProblemDetail */
        ProblemDetail: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Request Id */
            request_id: string;
            /** Field Errors */
            field_errors?: {
                [key: string]: string[];
            } | null;
            /** Retryable */
            retryable: boolean;
        };
        /** ProtocolRef */
        ProtocolRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
        };
        /**
         * PushRequest
         * @description POST /v1/sync/push envelope. Batch bound (50) matches
         *     api-contracts.md 'Common rules' - not an arbitrary number picked here.
         */
        PushRequest: {
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Events */
            events: (components["schemas"]["SampleCreateEvent"] | components["schemas"]["SampleCorrectEvent"])[];
        };
        /** RecordActionCommand */
        RecordActionCommand: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Expected Version */
            expected_version: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "record_action";
            payload: components["schemas"]["RecordActionPayload"];
        };
        /** RecordActionPayload */
        RecordActionPayload: {
            /** Description */
            description: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
        };
        /** RecordCommunicationCommand */
        RecordCommunicationCommand: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Expected Version */
            expected_version: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "record_communication";
            payload: components["schemas"]["RecordCommunicationPayload"];
        };
        /** RecordCommunicationPayload */
        RecordCommunicationPayload: {
            /** Channel */
            channel: string;
            /** Template Version */
            template_version: number;
            /** Audience Description */
            audience_description: string;
        };
        /** ReferToLabCommand */
        ReferToLabCommand: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Expected Version */
            expected_version: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "refer_to_lab";
            payload: components["schemas"]["ReferToLabPayload"];
        };
        /** ReferToLabPayload */
        ReferToLabPayload: {
            /** Lab Name */
            lab_name?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ReopenCommand */
        ReopenCommand: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Expected Version */
            expected_version: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "reopen";
            payload: components["schemas"]["ReopenPayload"];
        };
        /** ReopenPayload */
        ReopenPayload: {
            /** Reason */
            reason: string;
        };
        /** RequestClosureCommand */
        RequestClosureCommand: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Expected Version */
            expected_version: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "request_closure";
            payload: components["schemas"]["RequestClosurePayload"];
        };
        /** RequestClosurePayload */
        RequestClosurePayload: {
            /** Disposition */
            disposition?: string | null;
        };
        /** SampleCorrectEvent */
        SampleCorrectEvent: {
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "sample.correct";
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            payload: components["schemas"]["SampleCorrectionSampleV1"];
        };
        /**
         * SampleCorrectionSampleV1
         * @description sample.correct payload: same shape, plus the required pointer to the
         *     record it supersedes (data-model.md `samples.supersedes_id`).
         */
        SampleCorrectionSampleV1: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Sample Id
             * Format: uuid
             */
            sample_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            protocol: components["schemas"]["ProtocolRef"];
            /**
             * Kit Lot Id
             * Format: uuid
             */
            kit_lot_id: string;
            /**
             * Captured At Device
             * Format: date-time
             */
            captured_at_device: string;
            /** Timing */
            timing: components["schemas"]["TimingMeasured"] | components["schemas"]["TimingIndeterminate"];
            method: components["schemas"]["Method"];
            observation: components["schemas"]["Observation"];
            /** Evidence Ids */
            evidence_ids?: string[];
            /** Client Build */
            client_build: string;
            data_mode: components["schemas"]["DataMode"];
            /**
             * Supersedes Id
             * Format: uuid
             */
            supersedes_id: string;
        };
        /** SampleCreateEvent */
        SampleCreateEvent: {
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "sample.create";
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            payload: components["schemas"]["CanonicalSampleV1"];
        };
        /**
         * TimingIndeterminate
         * @description Elapsed time could NOT be established (reboot, clock change, ...).
         *
         *     Deliberately has NO `elapsed_ms`. The previous v1 shape required one, so
         *     a rebooted test could only be recorded by inventing a number
         *     (`elapsed_ms=0`) — fabricated precision, forbidden by AGENTS.md. Absence of
         *     the field is the only honest representation of "unknown".
         */
        TimingIndeterminate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            state: "indeterminate";
            /**
             * Reason
             * @enum {string}
             */
            reason: "reboot" | "clock_rollback" | "clock_disagreement" | "monotonic_regression" | "read_window_malformed";
            /**
             * Valid
             * @default false
             * @constant
             */
            valid: false;
        };
        /**
         * TimingMeasured
         * @description Elapsed time was genuinely measured on a trustworthy clock.
         *
         *     `valid` is not free for the client to assert: it must equal
         *     `state == "in_window"`, enforced below. protocol-schema.md makes the
         *     in-window case the ONLY valid one, so a client cannot send
         *     `state="expired", valid=true` and have the server believe it.
         */
        TimingMeasured: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            state: "expired" | "in_window" | "late" | "preparing" | "waiting";
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Valid */
            valid: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sync_push_v1_sync_push_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    case_command_v1_cases__case_id__commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignCommand"] | components["schemas"]["ReferToLabCommand"] | components["schemas"]["RecordActionCommand"] | components["schemas"]["AcceptActionCommand"] | components["schemas"]["LinkRetestCommand"] | components["schemas"]["RecordCommunicationCommand"] | components["schemas"]["RequestClosureCommand"] | components["schemas"]["CloseCommand"] | components["schemas"]["ReopenCommand"] | components["schemas"]["DismissCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
